import type { InsightTemplate } from "./types";

/**
 * Insight templates. Display text lives in locales under insights.templates.{id}
 * with placeholders: {{joy}}, {{vice}}, {{mood}}, {{score}}, {{bandLabel}}, {{timeNote}}.
 */
export const INSIGHT_TEMPLATES: InsightTemplate[] = [
  {
    id: "aristocrat-tired",
    bands: ["high", "legendary"],
    preferTags: ["caffeine", "ritual", "rest", "boundaries"],
    preferCategoryPairs: [
      ["food", "habits"],
      ["home", "habits"],
    ],
    preferMoodTags: ["low-energy", "elegant", "rest"],
  },
  {
    id: "chaos-comfort-pact",
    bands: ["mid", "high"],
    preferTags: ["chaos", "comfort", "indulgence"],
    preferCategoryPairs: [
      ["habits", "food"],
      ["habits", "home"],
    ],
    preferMoodTags: ["chaos", "overwhelm", "messy"],
  },
  {
    id: "order-freak-softie",
    bands: ["high", "legendary"],
    preferTags: ["order", "focus", "reset"],
    preferCategoryPairs: [
      ["home", "stuff"],
      ["home", "habits"],
    ],
    preferMoodTags: ["focus", "sharp"],
  },
  {
    id: "sensory-poet",
    bands: ["mid", "high", "legendary"],
    preferTags: ["sensory", "books", "nature", "atmosphere"],
    preferCategoryPairs: [
      ["stuff", "outdoors"],
      ["food", "moments"],
      ["home", "outdoors"],
    ],
    preferMoodTags: ["gentle", "reflective", "soft"],
  },
  {
    id: "city-luck-magnet",
    bands: ["high", "legendary"],
    preferTags: ["luck", "city", "flow", "adrenaline"],
    preferCategoryPairs: [
      ["moments", "outdoors"],
      ["moments", "habits"],
    ],
    preferMoodTags: ["up", "smug", "bright"],
  },
  {
    id: "introvert-treasury",
    bands: ["mid", "high"],
    preferTags: ["silence", "introvert", "privacy", "quiet"],
    preferCategoryPairs: [
      ["home", "habits"],
      ["home", "stuff"],
    ],
    preferMoodTags: ["introvert", "hide", "recover"],
  },
  {
    id: "treat-yourself-economist",
    bands: ["mid", "high"],
    preferTags: ["indulgence", "treat", "self-care", "sweet"],
    preferCategoryPairs: [
      ["food", "habits"],
      ["food", "stuff"],
    ],
    preferMoodTags: ["leisure", "treat", "indulgence"],
  },
  {
    id: "social-spark-lowkey",
    bands: ["mid", "high"],
    preferTags: ["social", "connection", "human"],
    preferCategoryPairs: [
      ["food", "moments"],
      ["moments", "outdoors"],
    ],
    preferMoodTags: ["social", "outgoing", "connection"],
  },
  {
    id: "adulting-sidequest",
    bands: ["low", "mid"],
    preferTags: ["adulting", "practical", "work", "procrastination"],
    preferCategoryPairs: [
      ["home", "habits"],
      ["habits", "stuff"],
    ],
    preferMoodTags: ["work", "overwhelm", "wired"],
  },
  {
    id: "night-owl-diplomacy",
    bands: ["mid", "high"],
    preferTags: ["night", "secret", "digital"],
    preferCategoryPairs: [
      ["food", "habits"],
      ["habits", "home"],
    ],
    preferMoodTags: ["low-energy", "leisure", "hide"],
    preferTimes: ["night", "evening"],
  },
  {
    id: "flow-state-glitch",
    bands: ["high", "legendary"],
    preferTags: ["flow", "music", "focus", "sync"],
    preferCategoryPairs: [
      ["stuff", "moments"],
      ["outdoors", "moments"],
    ],
    preferMoodTags: ["focus", "flow", "up"],
  },
  {
    id: "soft-reset-protocol",
    bands: ["mid", "high"],
    preferTags: ["reset", "body", "air", "recovery"],
    preferCategoryPairs: [
      ["home", "outdoors"],
      ["food", "outdoors"],
    ],
    preferMoodTags: ["recover", "gentle", "reset"],
  },
  {
    id: "petty-joy-engine",
    bands: ["high", "legendary"],
    preferTags: ["small-win", "relief", "smug", "luck"],
    preferCategoryPairs: [
      ["moments", "habits"],
      ["moments", "home"],
    ],
    preferMoodTags: ["smug", "win", "spice"],
  },
  {
    id: "cozy-maximalist",
    bands: ["high", "legendary"],
    preferTags: ["comfort", "cozy", "warm", "luxury-small"],
    preferCategoryPairs: [
      ["home", "food"],
      ["home", "stuff"],
    ],
    preferMoodTags: ["rest", "leisure", "soft"],
  },
  {
    id: "boundary-artist",
    bands: ["mid", "high"],
    preferTags: ["boundaries", "cancel", "noise", "buffer"],
    preferCategoryPairs: [
      ["habits", "stuff"],
      ["habits", "moments"],
    ],
    preferMoodTags: ["introvert", "edge", "impatient"],
  },
  {
    id: "nostalgia-wifi",
    bands: ["mid", "high"],
    preferTags: ["nostalgia", "books", "memory", "emotion"],
    preferCategoryPairs: [
      ["stuff", "moments"],
      ["stuff", "food"],
    ],
    preferMoodTags: ["reflective", "soft-sad", "gentle"],
  },
  {
    id: "energy-mismatch-comedy",
    bands: ["low", "mid"],
    preferTags: ["caffeine", "rest", "adrenaline"],
    preferCategoryPairs: [
      ["food", "home"],
      ["moments", "habits"],
    ],
    preferMoodTags: ["wired", "low-energy", "messy"],
  },
  {
    id: "gratitude-bug",
    bands: ["legendary"],
    preferTags: ["beauty", "pause", "connection", "hope"],
    preferCategoryPairs: [
      ["moments", "outdoors"],
      ["food", "home"],
    ],
    preferMoodTags: ["gratitude", "up", "hope"],
  },
  {
    id: "practical-romantic",
    bands: ["mid", "high"],
    preferTags: ["practical", "object-love", "ritual", "precision"],
    preferCategoryPairs: [
      ["stuff", "home"],
      ["food", "stuff"],
    ],
    preferMoodTags: ["gentle", "focus", "sharp"],
  },
  {
    id: "weekend-philosopher",
    bands: ["high", "legendary"],
    preferTags: ["slow", "pause", "leisure", "browse"],
    preferCategoryPairs: [
      ["outdoors", "food"],
      ["home", "outdoors"],
    ],
    preferMoodTags: ["leisure", "loose", "reflective"],
  },
  {
    id: "caffeine-diplomat",
    bands: ["mid", "high", "legendary"],
    preferTags: ["caffeine", "morning", "ritual"],
    preferCategoryPairs: [
      ["food", "habits"],
      ["food", "moments"],
    ],
    preferMoodTags: ["wired", "up", "work"],
    preferTimes: ["morning"],
  },
  {
    id: "procrastination-poet",
    bands: ["low", "mid", "high"],
    preferTags: ["procrastination", "avoidance", "digital", "chaos"],
    preferCategoryPairs: [
      ["habits", "stuff"],
      ["habits", "home"],
    ],
    preferMoodTags: ["messy", "overwhelm", "leisure"],
  },
  {
    id: "tiny-luxury-board",
    bands: ["high", "legendary"],
    preferTags: ["luxury-small", "object-love", "treat", "comfort"],
    preferCategoryPairs: [
      ["stuff", "food"],
      ["stuff", "home"],
    ],
    preferMoodTags: ["soft", "elegant", "treat"],
  },
  {
    id: "urban-zen-glitch",
    bands: ["mid", "high"],
    preferTags: ["city", "quiet", "pause", "nature"],
    preferCategoryPairs: [
      ["moments", "outdoors"],
      ["outdoors", "home"],
    ],
    preferMoodTags: ["gentle", "recover", "focus"],
  },
  {
    id: "parent-stealth-mode",
    bands: ["mid", "high", "legendary"],
    preferTags: ["parenting", "silence", "night", "relief"],
    preferCategoryPairs: [
      ["home", "habits"],
      ["home", "food"],
    ],
    preferMoodTags: ["recover", "hide", "rest"],
    preferTimes: ["evening", "night"],
  },
  {
    id: "deadline-acrobat",
    bands: ["low", "mid"],
    preferTags: ["work", "adrenaline", "chaos", "focus"],
    preferCategoryPairs: [
      ["habits", "moments"],
      ["home", "habits"],
    ],
    preferMoodTags: ["wired", "impatient", "work"],
    preferTimes: ["afternoon"],
  },
  {
    id: "comfort-food-philosopher",
    bands: ["mid", "high"],
    preferTags: ["comfort", "sweet", "warm", "food-adjacent"],
    preferCategoryPairs: [
      ["food", "home"],
      ["food", "habits"],
    ],
    preferMoodTags: ["soft", "soft-sad", "leisure"],
  },
  {
    id: "playlist-oracle",
    bands: ["high", "legendary"],
    preferTags: ["music", "emotion", "sync", "mood"],
    preferCategoryPairs: [
      ["stuff", "moments"],
      ["stuff", "habits"],
    ],
    preferMoodTags: ["up", "reflective", "bright"],
  },
  {
    id: "inbox-illusionist",
    bands: ["low", "mid", "high"],
    preferTags: ["order", "digital", "work", "relief"],
    preferCategoryPairs: [
      ["home", "habits"],
      ["habits", "stuff"],
    ],
    preferMoodTags: ["focus", "work", "overwhelm"],
  },
  {
    id: "weather-mood-sync",
    bands: ["mid", "high"],
    preferTags: ["weather", "cozy", "air", "sensory"],
    preferCategoryPairs: [
      ["moments", "home"],
      ["outdoors", "food"],
    ],
    preferMoodTags: ["gentle", "soft", "reflective"],
  },
  {
    id: "social-battery-math",
    bands: ["mid", "high"],
    preferTags: ["social", "boundaries", "introvert", "connection"],
    preferCategoryPairs: [
      ["moments", "habits"],
      ["food", "moments"],
    ],
    preferMoodTags: ["social", "introvert", "recover"],
  },
  {
    id: "micro-win-collector",
    bands: ["high", "legendary"],
    preferTags: ["small-win", "luck", "precision", "adulting"],
    preferCategoryPairs: [
      ["moments", "home"],
      ["moments", "stuff"],
    ],
    preferMoodTags: ["smug", "up", "win"],
  },
  {
    id: "soft-chaos-engineer",
    bands: ["mid", "high"],
    preferTags: ["chaos", "order", "reset", "quirky"],
    preferCategoryPairs: [
      ["habits", "home"],
      ["habits", "outdoors"],
    ],
    preferMoodTags: ["messy", "wired", "focus"],
  },
  {
    id: "body-reset-sage",
    bands: ["mid", "high"],
    preferTags: ["body", "reset", "recovery", "walk"],
    preferCategoryPairs: [
      ["outdoors", "home"],
      ["food", "outdoors"],
    ],
    preferMoodTags: ["recover", "gentle", "reset"],
    preferTimes: ["morning"],
  },
  {
    id: "secret-snack-council",
    bands: ["mid", "high"],
    preferTags: ["secret", "night", "indulgence", "sweet"],
    preferCategoryPairs: [
      ["food", "habits"],
      ["food", "home"],
    ],
    preferMoodTags: ["hide", "leisure", "treat"],
    preferTimes: ["night"],
  },
  {
    id: "generic-high",
    bands: ["high", "legendary"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "generic-mid",
    bands: ["mid"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "generic-low",
    bands: ["low"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "generic-high-alt",
    bands: ["high", "legendary"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "generic-mid-alt",
    bands: ["mid"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "generic-low-alt",
    bands: ["low"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "roast-gentle",
    bands: ["low", "mid"],
    preferTags: ["chaos", "avoidance", "digital"],
    preferCategoryPairs: [],
    preferMoodTags: ["overwhelm", "messy", "wired"],
  },
  {
    id: "roast-soft-praise",
    bands: ["mid", "high"],
    preferTags: ["self-care", "comfort", "boundaries"],
    preferCategoryPairs: [],
    preferMoodTags: ["soft", "recover", "rest"],
  },
  {
    id: "roast-caffeine",
    bands: ["low", "mid", "high"],
    preferTags: ["caffeine", "wired", "morning"],
    preferCategoryPairs: [],
    preferMoodTags: ["wired", "work"],
    preferTimes: ["morning", "afternoon"],
  },
  {
    id: "roast-procrastinate",
    bands: ["low", "mid"],
    preferTags: ["procrastination", "avoidance", "scroll"],
    preferCategoryPairs: [],
    preferMoodTags: ["messy", "leisure"],
  },
  {
    id: "roast-overthink",
    bands: ["low", "mid", "high"],
    preferTags: ["rumination", "mind", "digital"],
    preferCategoryPairs: [],
    preferMoodTags: ["reflective", "overwhelm"],
  },
  {
    id: "roast-cozy-trap",
    bands: ["mid", "high"],
    preferTags: ["comfort", "sofa", "rest"],
    preferCategoryPairs: [],
    preferMoodTags: ["rest", "leisure"],
  },
  {
    id: "wisdom-small-joys",
    bands: ["mid", "high", "legendary"],
    preferTags: ["small-win", "ritual", "pause"],
    preferCategoryPairs: [],
    preferMoodTags: ["gentle", "gratitude"],
  },
  {
    id: "wisdom-boundaries",
    bands: ["mid", "high"],
    preferTags: ["boundaries", "cancel", "quiet"],
    preferCategoryPairs: [],
    preferMoodTags: ["introvert", "recover"],
  },
  {
    id: "wisdom-imperfect",
    bands: ["low", "mid"],
    preferTags: ["chaos", "messy", "human"],
    preferCategoryPairs: [],
    preferMoodTags: ["soft", "overwhelm"],
  },
  {
    id: "wisdom-rest-is-data",
    bands: ["high", "legendary"],
    preferTags: ["rest", "recovery", "silence"],
    preferCategoryPairs: [],
    preferMoodTags: ["rest", "recover"],
  },
  {
    id: "deep-dive-synergy",
    bands: ["high", "legendary"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "deep-dive-tension",
    bands: ["low", "mid"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "deep-dive-balance",
    bands: ["mid", "high"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "deep-dive-ops",
    bands: ["mid", "high", "legendary"],
    preferTags: [],
    preferCategoryPairs: [],
    preferMoodTags: [],
  },
  {
    id: "time-morning-launch",
    bands: ["mid", "high", "legendary"],
    preferTags: ["morning", "ritual", "caffeine"],
    preferCategoryPairs: [],
    preferMoodTags: [],
    preferTimes: ["morning"],
  },
  {
    id: "time-afternoon-dip",
    bands: ["low", "mid", "high"],
    preferTags: ["work", "reset", "snack"],
    preferCategoryPairs: [],
    preferMoodTags: [],
    preferTimes: ["afternoon"],
  },
  {
    id: "time-evening-unwind",
    bands: ["mid", "high", "legendary"],
    preferTags: ["evening", "comfort", "slow"],
    preferCategoryPairs: [],
    preferMoodTags: [],
    preferTimes: ["evening"],
  },
  {
    id: "time-night-council",
    bands: ["low", "mid", "high", "legendary"],
    preferTags: ["night", "secret", "digital"],
    preferCategoryPairs: [],
    preferMoodTags: [],
    preferTimes: ["night"],
  },
];

/** Locale keys under matchup.insights.{id} — {{left}}, {{right}}, {{score}}, {{friction}}. */
export const MATCHUP_INSIGHT_IDS = [
  "harmony-duo",
  "synergy-ritual",
  "synergy-soft-power",
  "synergy-city-flow",
  "productive-sparks",
  "productive-tension",
  "productive-engine",
  "friction-versus",
  "friction-clash",
  "friction-comedy",
  "friction-schedule-war",
  "duo-comfort-chaos",
  "duo-focus-treat",
  "duo-quiet-loud",
  "versus-energy-gap",
  "versus-priority-fight",
] as const;

/** Locale keys under weekly.titles.{id}. */
export const WEEKLY_TITLE_IDS = [
  "weekly-survivor-caffeine",
  "weekly-chaos-ops",
  "weekly-cozy-protocol",
  "weekly-social-surge",
  "weekly-quiet-bunker",
  "weekly-luck-streak",
  "weekly-soft-reboot",
  "weekly-engineer-status",
  "weekly-balanced-build",
  "weekly-generic-alpha",
  "weekly-generic-beta",
  "weekly-generic-gamma",
  "weekly-indulgence-sprint",
  "weekly-boundary-patch",
] as const;

/** Locale keys under weekly.summaries.{id} — {{a}}, {{b}}, {{c}}, {{score}}, {{bandLabel}}. */
export const WEEKLY_SUMMARY_IDS = [
  "ops-log-1",
  "ops-log-2",
  "ops-log-3",
  "ops-log-4",
  "ops-log-5",
  "ops-log-6",
  "ops-log-7",
  "ops-log-8",
] as const;
